# -*- coding: utf-8 -*-
"""Tarefa1_DeepLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15seWBxJjBQ38BUu_rjtNd9uhbIh4813u
"""

import kagglehub #

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader #
import torchvision.transforms as transforms #
import torchvision.transforms.functional as TF #
from torchvision.models.segmentation import deeplabv3_resnet50
from torchvision.io import read_image #

!pip install torch-summary
from torchsummary import summary

import numpy as np #
import pandas as pd #
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
import cv2
from sklearn.metrics import confusion_matrix
import os
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

# Set device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

"""# Importando os dados"""

carlolepelaars_camvid_path = kagglehub.dataset_download('carlolepelaars/camvid')

base_path = "/kaggle/input/camvid/CamVid/"

class_dict = pd.read_csv(os.path.join(base_path, "class_dict.csv"))
class_dict.head(5)

"""# Testes"""

# Teste de leitura de imagem
files = os.listdir(base_path + 'train')

image_tensor_sample = read_image(os.path.join(base_path, 'train/', files[0]))

print(image_tensor_sample.shape)

print("------------------------------")

rgb_channels, height, lenght = image_tensor_sample.shape

print(rgb_channels, height, lenght)

"""# Definição do dataset

A custom Dataset class must implement three functions: __init__, __len__, and __getitem__
"""

# =========================================================
# Configurações para o modelo
# =========================================================

batch_size = 8

# =========================================================
# Implementação do dataset
# =========================================================

class SegmentationDataset(Dataset):
    def __init__(self, images_dir, masks_dir, transform=None, target_transform=None, in_memory = False):
        self.in_memory = in_memory
        self.images_dir = images_dir
        self.masks_dir = masks_dir
        self.transform = transform
        self.target_transform = target_transform
        self.images = []
        self.masks = []
        self.images_files = os.listdir(images_dir) #Posso usar aqui para controlar o tamanho do dataset (os.listdir(images_dir)[0:30])

        # Pré-carregamento na CPU para maior velociade
        if in_memory:
            for img_name in self.images_files:
                img_path = os.path.join(images_dir, img_name)
                mask_path = os.path.join(masks_dir, img_name.replace('.png', '_L.png'))

                # Read
                image = read_image(img_path).float() / 255.0  # já normalizado
                mask = read_image(mask_path)

                # Save in RAM memory
                self.images.append(image)
                self.masks.append(mask)

            #print("All images in Memory")

        self.rgb_values = torch.tensor(class_dict[['r', 'g', 'b']].values, dtype=torch.uint8).to(device)

    # Retorna o tamanho do dataset
    def __len__(self):
            return len(self.images_files)

    # Retorna uma imagem e uma label, dado um index
    def __getitem__(self, idx):
        if self.in_memory:
            image = self.images[idx].to(device) # Move image to GPU
            mask = self.masks[idx].to(device)
        else:
            img_name = self.images_files[idx]
            img_path = os.path.join(self.images_dir, img_name)
            mask_path = os.path.join(self.masks_dir, img_name.replace('.png', '_L.png'))

            # Load the image and mask
            image = read_image(img_path).to(device)  # Read and move image to GPU
            mask = read_image(mask_path).to(device)

        if self.transform:
            image = self.transform(image)
        if self.target_transform:
            mask = self.target_transform(mask)

        mask = self.mask_to_label(mask.permute(1,2,0))

        return image / 255 , mask

    def mask_to_label(self, img):
        # Get the width, height of the image (assuming img has shape [H, W, 3])
        h, w, _ = img.shape
        # Create an empty tensor
        labels = torch.zeros(h, w, device=device, dtype=torch.long)

        # Iterate over each class and map the pixels
        for i, color in enumerate(self.rgb_values):
            match = torch.all(torch.abs((img - color)) == 0, axis = -1)
            labels[match] = i

        return labels

# Mask transformation
transform_target = transforms.Compose([
    transforms.Resize(
            (height // 2, lenght // 2),
            interpolation=Image.NEAREST)
])

# Train transformation
transform = transforms.Compose([
    transforms.Resize(
            (height // 2, lenght // 2),
            antialias=True,
            interpolation=Image.BILINEAR)
])

# Datasets
train_dataset = SegmentationDataset(images_dir=base_path + '/train', masks_dir=base_path + 'train_labels', transform=transform, target_transform = transform)
val_dataset = SegmentationDataset(images_dir=base_path + '/val', masks_dir=base_path + 'val_labels', transform=transform, target_transform = transform_target)
test_dataset = SegmentationDataset(images_dir=base_path + '/test', masks_dir=base_path + 'test_labels', transform=transform, target_transform = transform_target)

# DataLoaders
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0)

print(f"Train dataset size: {len(train_dataset)}")
print(f"Validation dataset size: {len(val_dataset)}")
print(f"Test dataset size: {len(test_dataset)}")

"""## Tamanho dos tensores"""

print(f"Tamanho do tensor de entrada: {train_dataset[0][1].shape}")
print(f"Tamanho do tensor de saída: {train_dataset[0][0].shape}")

"""# Funções Auxiliares"""

class_to_rgb = {idx: (row['r'], row['g'], row['b']) for idx, row in class_dict.iterrows()}

def class_to_rgb_mask(mask, class_to_rgb):
    h, w = mask.shape
    rgb_mask = np.zeros((h, w, 3), dtype=np.uint8)

    for class_idx, rgb in class_to_rgb.items():
        rgb_mask[mask == class_idx] = rgb

    return rgb_mask

def plot_predictions(image, predicted_mask, ground_truth_mask):
    predicted_rgb = class_to_rgb_mask(predicted_mask, class_to_rgb)
    ground_truth_rgb = class_to_rgb_mask(ground_truth_mask, class_to_rgb)

    image_np = image.permute(1, 2, 0).cpu().numpy()

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    # Original image
    axes[0].imshow(image_np)
    axes[0].set_title("Original Image")
    axes[0].axis('off')

    # Ground Truth
    axes[1].imshow(ground_truth_rgb)
    axes[1].set_title("Ground Truth Mask")
    axes[1].axis('off')

    # Class mask
    axes[2].imshow(predicted_rgb)
    axes[2].set_title("Predicted Mask")
    axes[2].axis('off')

    plt.tight_layout()
    plt.show()

def save_checkpoint(model, optimizer, epoch, loss, file_path):
    checkpoint = {
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'loss': loss
    }

    torch.save(checkpoint, file_path)

    print(f'Checkpoint saved to {file_path}')

# Exemplo
plot_predictions(train_dataset[0][0], train_dataset[0][1], train_dataset[0][1])

"""# U-Net arquitetura"""

class DoubleConv(nn.Module):
    """Double Convolution block used in U-Net"""
    def __init__(self, in_channels, out_channels, padding = 1, stride = 1): #esse padding e stride mantem o tamanho da imagem para kernel 3x3
        super(DoubleConv, self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size = 3, padding=padding, stride = padding), # mudar o padding para diminuir a imagem (padding = 0 diminui 2 a cada convolução)
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size = 3, padding=padding, stride = padding),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        return self.conv(x)

class Down(nn.Module):
    """Downsampling block"""
    def __init__(self, in_channels, out_channels):
        super(Down, self).__init__()
        self.maxpool_conv = nn.Sequential(
            nn.MaxPool2d(2),
            DoubleConv(in_channels, out_channels) #alterar padding e stride se quiser (padding = 0)
        )

    def forward(self, x):
        return self.maxpool_conv(x)

class Up(nn.Module):
    def __init__(self, in_channels, skip_channels, out_channels, bilinear=False):
        super(Up, self).__init__()
        self.bilinear = bilinear
        if bilinear:
            self.up = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
            self.conv = DoubleConv(in_channels + skip_channels, out_channels)
        else:
            self.up = nn.ConvTranspose2d(in_channels, in_channels // 2, kernel_size=2, stride=2) #upsampling - por isso kernel 2
            self.conv = DoubleConv((in_channels // 2) + skip_channels, out_channels) #alterar padding e stride se quiser (padding = 2)

    def forward(self, x1, x2):
        x1 = self.up(x1)
        x1 = F.interpolate(x1, size=x2.shape[2:], mode='bilinear', align_corners=True)
        x = torch.cat([x2, x1], dim=1)
        return self.conv(x)


class UNet(nn.Module):
    """U-Net implementation with configurable depth"""
    def __init__(self, n_channels=3, n_classes=32, depth=4, base_channels=64, bilinear=False):
        super(UNet, self).__init__()
        self.n_channels = n_channels
        self.n_classes = n_classes
        self.depth = depth
        self.bilinear = bilinear

        #--------------------- Model -----------------------

        # Initial convolution
        self.inc = DoubleConv(n_channels, base_channels)

        # Encoder (downsampling path)
        self.downs = nn.ModuleList()
        in_ch = base_channels
        for i in range(depth):
            out_ch = base_channels * (2 ** (i + 1))
            self.downs.append(Down(in_ch, out_ch))
            in_ch = out_ch

        # Decoder (upsampling path)
        self.ups = nn.ModuleList()
        for i in range(depth):
            skip_ch = base_channels * (2 ** (depth - i - 1))
            if i == 0:
                up_ch = base_channels * (2 ** depth)
            else:
                up_ch = out_ch

            out_ch = skip_ch
            self.ups.append(Up(up_ch, skip_ch, out_ch, bilinear=True))

        # Final classification layer
        self.outc = nn.Conv2d(base_channels, n_classes, kernel_size=1)

        #--------------------- Model -----------------------

        # Calculate number of parameters
        self.num_params = sum(p.numel() for p in self.parameters())

    def forward(self, x):
        # Initial convolution
        x1 = self.inc(x)

        # Store skip connections
        skip_connections = [x1]

        # Encoder path
        x = x1
        for down in self.downs:
            x = down(x)
            skip_connections.append(x)

        # Decoder path
        for i, up in enumerate(self.ups):
            if i == 0:
                # First upsampling (from bottleneck)
                x = up(x, skip_connections[-(i + 2)])
            else:
                x = up(x, skip_connections[-(i + 2)])

        # Final classification
        logits = self.outc(x)
        return logits

    def get_num_parameters(self):
        return self.num_params

num_classes = len(class_dict)

# Test different U-Net depths
depths = [3, 4, 5]
for depth in depths:
    model = UNet(n_channels=3, n_classes=num_classes, depth=depth, base_channels=32)
    print(f"U-Net depth {depth}: {model.get_num_parameters():,} parameters")

# Create the main model
model = UNet(n_channels=3, n_classes=num_classes, depth=3, base_channels=32).to(device)
print(f"\nMain U-Net model created with {model.get_num_parameters():,} parameters")

"""# Entendendo o modelo"""

summary(model);

def compute_global_accuracy(model, data_loader):
    model.eval()  # Set the model to evaluation mode
    correct_pixels = 0
    total_pixels = 0

    with torch.no_grad():  # No need to compute gradients for evaluation
        for images, masks in data_loader:
            images, masks = images.to(device), masks.to(device)

            # Forward pass: get predictions
            outputs = model(images)
            preds = torch.argmax(outputs, dim=1)  # Get the predicted class for each pixel

            # Compare predictions to ground truth
            correct_pixels += torch.sum(preds == masks).item()
            total_pixels += masks.numel()  # Total number of pixels in the batch

    # Compute global accuracy
    global_accuracy = correct_pixels / total_pixels
    return global_accuracy

def compute_per_class_accuracy(model, data_loader, num_classes):
    model.eval()
    class_correct = torch.zeros(num_classes).to(device)
    class_total = torch.zeros(num_classes).to(device)

    with torch.no_grad():
        for images, masks in data_loader:
            images, masks = images.to(device), masks.to(device)

            outputs = model(images)
            preds = torch.argmax(outputs, dim=1)  # Get the predicted class for each pixel

            for cls in range(num_classes):
                # True for correctly predicted pixels of class cls
                class_mask = (masks == cls)

                # Count correct predictions for this class
                class_correct[cls] += torch.sum((preds == cls) & class_mask).float()

                # Count total number of pixels of this class in the ground truth
                class_total[cls] += torch.sum(class_mask).float()

    # Compute accuracy per class (avoid division by zero)
    per_class_accuracy = class_correct / (class_total + 1e-6)  # Add a small epsilon to avoid division by zero
    return per_class_accuracy.cpu().numpy()  # Return per-class accuracy as a numpy array

import torch

def compute_dice_per_class(preds, masks, num_classes):
    dice_per_class = []

    for cls in range(num_classes):
        pred_cls = (preds == cls)
        target_cls = (masks == cls)

        intersection = torch.sum(pred_cls & target_cls).float()
        dice = (2 * intersection) / (torch.sum(pred_cls) + torch.sum(target_cls)).float()

        if torch.sum(pred_cls) == 0 and torch.sum(target_cls) == 0:
            dice_per_class.append(float('nan'))  # Avoid NaN when no prediction or ground truth exists
        else:
            dice_per_class.append(dice.item())

    return dice_per_class

def compute_mean_dice(model, data_loader, num_classes):
    model.eval()
    total_dice = torch.zeros(num_classes).to(device)
    count_per_class = torch.zeros(num_classes).to(device)

    with torch.no_grad():
        for images, masks in data_loader:
            images, masks = images.to(device), masks.to(device)

            outputs = model(images)
            preds = torch.argmax(outputs, dim=1)

            dice_per_class = compute_dice_per_class(preds, masks, num_classes)
            dice_per_class_tensor = torch.tensor(dice_per_class).to(device)

            # Update total_dice and count for non-NaN values
            valid_mask = ~torch.isnan(dice_per_class_tensor)
            total_dice += torch.where(valid_mask, dice_per_class_tensor, torch.zeros_like(dice_per_class_tensor))
            count_per_class += valid_mask.float()

    # Compute per-class Dice by averaging the total Dice for each class
    avg_dice_per_class = total_dice / count_per_class
    mean_dice = torch.nanmean(avg_dice_per_class)  # Mean Dice across all classes, ignoring NaNs

    return mean_dice.item(), avg_dice_per_class.cpu().tolist()  # Return both mean and per-class Dice


def compute_iou_per_class(preds, masks, num_classes):
    iou_per_class = []

    for cls in range(num_classes):
        pred_cls = (preds == cls)
        target_cls = (masks == cls)

        intersection = torch.sum(pred_cls & target_cls).float()
        union = torch.sum(pred_cls | target_cls).float()

        if union == 0:
            iou_per_class.append(float('nan'))  # Avoid division by zero
        else:
            iou_per_class.append((intersection / union).item())

    return iou_per_class

def compute_mean_iou(model, data_loader, num_classes):
    model.eval()
    total_iou = torch.zeros(num_classes).to(device)
    count_per_class = torch.zeros(num_classes).to(device)

    with torch.no_grad():
        for images, masks in data_loader:
            images, masks = images.to(device), masks.to(device)

            outputs = model(images)
            preds = torch.argmax(outputs, dim=1)

            iou_per_class = compute_iou_per_class(preds, masks, num_classes)
            iou_per_class_tensor = torch.tensor(iou_per_class).to(device)

            # Update total_iou and count for non-NaN values
            valid_mask = ~torch.isnan(iou_per_class_tensor)
            total_iou += torch.where(valid_mask, iou_per_class_tensor, torch.zeros_like(iou_per_class_tensor))
            count_per_class += valid_mask.float()

    # Compute per-class IoU by averaging the total IoU for each class
    avg_iou_per_class = total_iou / count_per_class
    mean_iou = torch.nanmean(avg_iou_per_class)  # Mean IoU across all classes, ignoring NaNs

    return mean_iou.item(), avg_iou_per_class.cpu().tolist()  # Return both mean and per-class IoU

#%%
"""# Classe Trainer e Funções de Treinamento"""

import time
from collections import defaultdict

class FocalLoss(nn.Module):
    """Implementação da Focal Loss para segmentação semântica"""
    def __init__(self, alpha=1, gamma=2, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, inputs, targets):
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')
        pt = torch.exp(-ce_loss)
        focal_loss = self.alpha * (1-pt)**self.gamma * ce_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        else:
            return focal_loss

class Trainer:
    """Classe para treinar modelos de segmentação semântica"""

    def __init__(self, model, train_loader, val_loader, test_loader, num_classes, device):
        self.model = model
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.test_loader = test_loader
        self.num_classes = num_classes
        self.device = device

        # Histórico de treinamento
        self.train_losses = []
        self.val_losses = []
        self.val_accuracies = []
        self.val_ious = []

    def train_epoch(self, optimizer, criterion, epoch, plot_images=False):
        """Treina por uma época"""
        self.model.train()
        running_loss = 0.0

        pbar = tqdm(self.train_loader, desc=f'Época {epoch+1}')
        for batch_idx, (images, masks) in enumerate(pbar):
            images, masks = images.to(self.device), masks.to(self.device)

            # Zero gradients
            optimizer.zero_grad()

            # Forward pass
            outputs = self.model(images)
            loss = criterion(outputs, masks)

            # Backward pass
            loss.backward()
            optimizer.step()

            running_loss += loss.item()

            # Atualizar barra de progresso
            pbar.set_postfix({'Loss': f'{loss.item():.4f}'})

            # Plotar imagens a cada 5 épocas se solicitado
            if plot_images and epoch % 5 == 0 and batch_idx == 0:
                with torch.no_grad():
                    preds = torch.argmax(outputs, dim=1)
                    plot_predictions(images[0], preds[0].cpu().numpy(), masks[0].cpu().numpy())

        epoch_loss = running_loss / len(self.train_loader)
        return epoch_loss

    def validate(self, criterion):
        """Valida o modelo"""
        self.model.eval()
        running_loss = 0.0

        with torch.no_grad():
            for images, masks in self.val_loader:
                images, masks = images.to(self.device), masks.to(self.device)
                outputs = self.model(images)
                loss = criterion(outputs, masks)
                running_loss += loss.item()

        val_loss = running_loss / len(self.val_loader)

        # Calcular métricas
        val_accuracy = compute_global_accuracy(self.model, self.val_loader)
        val_iou, _ = compute_mean_iou(self.model, self.val_loader, self.num_classes)

        return val_loss, val_accuracy, val_iou

    def train(self, optimizer, criterion, epochs, checkpoint_dir="checkpoints", plot_images=False):
        """Função principal de treinamento"""
        print(f"🚀 Iniciando treinamento por {epochs} épocas...")
        print(f"📊 Modelo: {self.model.__class__.__name__}")
        print(f"🔧 Otimizador: {optimizer.__class__.__name__}")
        print(f"📉 Critério: {criterion.__class__.__name__}")
        print(f"💾 Checkpoints salvos em: {checkpoint_dir}")
        print("-" * 50)

        # Criar diretório de checkpoints
        os.makedirs(checkpoint_dir, exist_ok=True)

        best_val_iou = 0.0
        start_time = time.time()

        for epoch in range(epochs):
            # Treinar
            train_loss = self.train_epoch(optimizer, criterion, epoch, plot_images)

            # Validar
            val_loss, val_accuracy, val_iou = self.validate(criterion)

            # Salvar histórico
            self.train_losses.append(train_loss)
            self.val_losses.append(val_loss)
            self.val_accuracies.append(val_accuracy)
            self.val_ious.append(val_iou)

            # Print do progresso
            print(f"Época {epoch+1:3d}/{epochs} | "
                  f"Train Loss: {train_loss:.4f} | "
                  f"Val Loss: {val_loss:.4f} | "
                  f"Val Acc: {val_accuracy:.4f} | "
                  f"Val IoU: {val_iou:.4f}")

            # Salvar melhor modelo
            if val_iou > best_val_iou:
                best_val_iou = val_iou
                best_model_path = os.path.join(checkpoint_dir, "best_model.pth")
                save_checkpoint(self.model, optimizer, epoch, val_loss, best_model_path)
                print(f"✅ Novo melhor modelo salvo! IoU: {best_val_iou:.4f}")

            # Salvar checkpoint a cada 10 épocas
            if (epoch + 1) % 10 == 0:
                checkpoint_path = os.path.join(checkpoint_dir, f"checkpoint_epoch_{epoch+1}.pth")
                save_checkpoint(self.model, optimizer, epoch, val_loss, checkpoint_path)

        total_time = time.time() - start_time
        print(f"\n🎉 Treinamento concluído em {total_time/60:.2f} minutos!")
        print(f"🏆 Melhor IoU de validação: {best_val_iou:.4f}")

        return best_val_iou

    def plot_training_curves(self):
        """Plota curvas de treinamento"""
        fig, axes = plt.subplots(2, 2, figsize=(15, 10))

        # Loss
        axes[0,0].plot(self.train_losses, label='Train Loss', color='blue')
        axes[0,0].plot(self.val_losses, label='Val Loss', color='red')
        axes[0,0].set_title('Loss durante o treinamento')
        axes[0,0].set_xlabel('Época')
        axes[0,0].set_ylabel('Loss')
        axes[0,0].legend()
        axes[0,0].grid(True)

        # Accuracy
        axes[0,1].plot(self.val_accuracies, label='Val Accuracy', color='green')
        axes[0,1].set_title('Acurácia de Validação')
        axes[0,1].set_xlabel('Época')
        axes[0,1].set_ylabel('Acurácia')
        axes[0,1].legend()
        axes[0,1].grid(True)

        # IoU
        axes[1,0].plot(self.val_ious, label='Val IoU', color='purple')
        axes[1,0].set_title('IoU de Validação')
        axes[1,0].set_xlabel('Época')
        axes[1,0].set_ylabel('IoU')
        axes[1,0].legend()
        axes[1,0].grid(True)

        # Combinado
        ax_combined = axes[1,1]
        ax1 = ax_combined
        ax2 = ax1.twinx()

        line1 = ax1.plot(self.train_losses, 'b-', label='Train Loss')
        line2 = ax1.plot(self.val_losses, 'r-', label='Val Loss')
        line3 = ax2.plot(self.val_ious, 'g-', label='Val IoU')

        ax1.set_xlabel('Época')
        ax1.set_ylabel('Loss', color='b')
        ax2.set_ylabel('IoU', color='g')
        ax1.set_title('Loss vs IoU')

        # Combinar legendas
        lines = line1 + line2 + line3
        labels = [l.get_label() for l in lines]
        ax1.legend(lines, labels, loc='center right')

        plt.tight_layout()
        plt.show()

def test_model(model, test_loader, num_classes, device):
    """Testa o modelo no conjunto de teste"""
    print("🧪 Testando modelo...")

    # Métricas
    test_accuracy = compute_global_accuracy(model, test_loader)
    test_iou, _ = compute_mean_iou(model, test_loader, num_classes)
    test_dice, _ = compute_mean_dice(model, test_loader, num_classes)

    print(f"📊 Resultados no conjunto de teste:")
    print(f"   Acurácia Global: {test_accuracy:.4f}")
    print(f"   IoU Médio: {test_iou:.4f}")
    print(f"   Dice Médio: {test_dice:.4f}")

    return test_accuracy, test_iou, test_dice

# Função para criar modelo com parâmetros específicos
def create_model(base_channels=32, depth=3, num_classes=32, padding_encoder=1, padding_decoder=1):
    """Cria modelo U-Net com parâmetros específicos"""
    if padding_encoder != 1 or padding_decoder != 1:
        # Criar versão modificada da UNet com padding customizado
        class CustomUNet(UNet):
            def __init__(self, n_channels=3, n_classes=32, depth=4, base_channels=64,
                        padding_encoder=1, padding_decoder=1, bilinear=False):
                super().__init__(n_channels, n_classes, depth, base_channels, bilinear)

                # Recriar encoder com padding customizado
                self.inc = DoubleConv(n_channels, base_channels, padding=padding_encoder)

                self.downs = nn.ModuleList()
                in_ch = base_channels
                for i in range(depth):
                    out_ch = base_channels * (2 ** (i + 1))
                    down_block = nn.Sequential(
                        nn.MaxPool2d(2),
                        DoubleConv(in_ch, out_ch, padding=padding_encoder)
                    )
                    self.downs.append(down_block)
                    in_ch = out_ch

                # Recriar decoder com padding customizado
                self.ups = nn.ModuleList()
                for i in range(depth):
                    skip_ch = base_channels * (2 ** (depth - i - 1))
                    if i == 0:
                        up_ch = base_channels * (2 ** depth)
                    else:
                        up_ch = out_ch

                    out_ch = skip_ch
                    up_block = Up(up_ch, skip_ch, out_ch, bilinear=True, padding=padding_decoder)
                    self.ups.append(up_block)

        # Modificar a classe Up para aceitar padding customizado
        class CustomUp(Up):
            def __init__(self, in_channels, skip_channels, out_channels, bilinear=False, padding=1):
                super().__init__(in_channels, skip_channels, out_channels, bilinear)
                if bilinear:
                    self.conv = DoubleConv(in_channels + skip_channels, out_channels, padding=padding)
                else:
                    self.conv = DoubleConv((in_channels // 2) + skip_channels, out_channels, padding=padding)

        # Usar CustomUNet se padding diferente
        model = CustomUNet(n_channels=3, n_classes=num_classes, depth=depth,
                          base_channels=base_channels, padding_encoder=padding_encoder,
                          padding_decoder=padding_decoder)
    else:
        model = UNet(n_channels=3, n_classes=num_classes, depth=depth, base_channels=base_channels)

    return model.to(device)

# Dicionário para armazenar resultados dos experimentos
experiment_results = {}

#%%
#==========
# EXPERIMENTO 1: Base Channels
#==========
"""
Testando diferentes números de canais base: [8, 16, 32, 64]
Parâmetros fixos: depth=3, lr=0.001, AdamW, CrossEntropyLoss
"""

print("🔬 EXPERIMENTO 1: Testando diferentes Base Channels")
print("=" * 60)

base_channels_list = [8, 16, 32, 64]
epochs_exp = 20  # Número reduzido de épocas para experimentos

for base_channels in base_channels_list:
    print(f"\n🧪 Testando base_channels = {base_channels}")
    print("-" * 40)

    # Criar modelo
    model = create_model(base_channels=base_channels, depth=3, num_classes=num_classes)
    print(f"📊 Modelo criado com {model.get_num_parameters():,} parâmetros")

    # Criar trainer
    trainer = Trainer(model, train_loader, val_loader, test_loader, num_classes, device)

    # Configurar otimizador e critério
    optimizer = optim.AdamW(model.parameters(), lr=0.001, weight_decay=1e-4)
    criterion = nn.CrossEntropyLoss()

    # Treinar
    checkpoint_dir = f"experiments/exp1_channels_{base_channels}"
    best_iou = trainer.train(optimizer, criterion, epochs_exp, checkpoint_dir, plot_images=False)

    # Salvar resultados
    experiment_results[f"exp1_channels_{base_channels}"] = {
        'base_channels': base_channels,
        'depth': 3,
        'optimizer': 'AdamW',
        'lr': 0.001,
        'loss': 'CrossEntropyLoss',
        'best_val_iou': best_iou,
        'num_params': model.get_num_parameters(),
        'train_losses': trainer.train_losses.copy(),
        'val_losses': trainer.val_losses.copy(),
        'val_accuracies': trainer.val_accuracies.copy(),
        'val_ious': trainer.val_ious.copy()
    }

    # Plotar curvas de treinamento
    trainer.plot_training_curves()

    print(f"✅ Base channels {base_channels} concluído! Melhor IoU: {best_iou:.4f}")

# Encontrar melhor base_channels
best_channels_exp = max([(k, v['best_val_iou']) for k, v in experiment_results.items()
                        if 'exp1_channels' in k], key=lambda x: x[1])
best_base_channels = int(best_channels_exp[0].split('_')[-1])

print(f"\n🏆 RESULTADO EXPERIMENTO 1:")
print(f"Melhor base_channels: {best_base_channels} (IoU: {best_channels_exp[1]:.4f})")

# Tabela resumo do experimento 1
print(f"\n📊 RESUMO EXPERIMENTO 1:")
print("Base Channels | Parâmetros | Melhor IoU")
print("-" * 40)
for base_channels in base_channels_list:
    key = f"exp1_channels_{base_channels}"
    if key in experiment_results:
        result = experiment_results[key]
        print(f"{base_channels:12d} | {result['num_params']:9,d} | {result['best_val_iou']:8.4f}")

print("=" * 60)
